#!/usr/bin/env bash
# 将 Caddy 源站反代从旧 Lotus/Hyperf 切到 titancore-mirror :3000
# 用法: sudo bash scripts/fix-caddy-origin.sh
set -Eeuo pipefail

PORT="${PORT:-3000}"
BACKEND_PORT="${BACKEND_PORT:-9528}"
DOMAIN="${DOMAIN:-lotusscom.my}"

if [ "$(id -u)" -ne 0 ]; then
  echo "请用 root/sudo 执行"
  exit 1
fi

if ! command -v caddy >/dev/null 2>&1 && ! systemctl list-unit-files caddy.service >/dev/null 2>&1; then
  echo "未检测到 Caddy，跳过（仅 Nginx 生效时请确认 Cloudflare 回源端口为 80）"
  exit 0
fi

CADDYFILE=""
for f in /etc/caddy/Caddyfile /etc/Caddyfile; do
  if [ -f "$f" ]; then CADDYFILE="$f"; break; fi
done
if [ -z "$CADDYFILE" ]; then
  mkdir -p /etc/caddy
  CADDYFILE="/etc/caddy/Caddyfile"
fi

if [ -f "$CADDYFILE" ] && [ ! -f "${CADDYFILE}.bak.titancore" ]; then
  cp "$CADDYFILE" "${CADDYFILE}.bak.titancore"
  echo "已备份原 Caddyfile → ${CADDYFILE}.bak.titancore"
fi

cat > "$CADDYFILE" <<EOF
# titancore-mirror — auto-generated by fix-caddy-origin.sh
www.$DOMAIN, $DOMAIN {
    @api path /api/*
    handle @api {
        reverse_proxy 127.0.0.1:$BACKEND_PORT
    }
    handle {
        reverse_proxy 127.0.0.1:$PORT
    }
}
EOF

if command -v caddy >/dev/null 2>&1; then
  caddy validate --config "$CADDYFILE"
fi

systemctl enable caddy >/dev/null 2>&1 || true
systemctl reload caddy 2>/dev/null || systemctl restart caddy

echo "Caddy 已指向 127.0.0.1:$PORT（/api/ → $BACKEND_PORT）"
echo "验证: curl -s -H 'Host: www.$DOMAIN' http://127.0.0.1/ | head -c 200"
